# Generated by Django 4.0.6 on 2022-07-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('categories', models.JSONField()),
                ('region', models.IntegerField()),
                ('phone', models.CharField(max_length=100)),
                ('siteUrl', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
