# Generated by Django 4.0.6 on 2022-07-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0002_alter_company_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='categories',
            field=models.JSONField(default=list),
        ),
    ]
